### ISSUE TITLE
Media Queries removed

### ISSUE THREAD

**Issue by kijanawoodard** [janjongboom/Moth#15]
I'm working on a new MVC4 project. 
I used nuget to install Moth and setup global.asax as necessary. 

I added the following to _Layout.cshtml

@{ Html.RegisterStylesheet("~/content/styles/site.css"); }
@Html.RenderCss()

It all worked, but I noticed the styles were "funny".

It turns out that the "@media only screen and (max-width: 850px) {" was removed from the style sheet so the mobile styles were being applied always.

I'm guessing the minification/tidy is to blame. Advice?

**Comment by janjongboom** [comment]
Could be. Can you disable CssTidy, see the [Options](https://github.com/janjongboom/Moth/wiki/Options) page. Maybe I'm using an outdated version that strips media queries.

**Comment by kijanawoodard** [comment]
The short answer is that disabling CssTidy seems to fix the Media Queries problem.

However, another problem emerges that may be related to https://github.com/janjongboom/Moth/issues/4.

In the CustomMothProvide I used: 

```
    public override IOutputCacheRestrictions Enable
    {
        get
        {
            return new OutputCacheRestrictions()
            {
                PageOutput = true, 
                CssTidy = false,   
                ScriptMinification = false
            };
        }
    }
```

The media queries are intact as I said, but the images within the css are pointing to the "resources" folder. Apparently CssPreprocessing is defaulted to false. I added it to confirm that the behavior was the same:

```
            return new OutputCacheRestrictions()
            {
                PageOutput = true, 
                CssTidy = false,   
                ScriptMinification = false,
                CssPreprocessing = false 
            };
```

I figured, no problem, just set CssPreprocessing to true. Doing that causes the RenderCss to hang.

If I also set CssTidy to true, the RenderCss call works and the image urls within the css point to the correct folders. But then I'm back to my original problem of CssTidy removing the media queries. :-)

I hope this helps. Thanks for creating Moth. It gives us similar abilities to FubuMVCs asset pipeline in Asp.Net MVC.

**Comment by janjongboom** [comment]
Hmm weird. I'll have a look this weekend when I have a Windows machine :-). Thanks for the Moth love btw!

**Comment by kijanawoodard** [comment]
Sent a pull request that, hopefully, gets you going in the right direction

**Comment by kijanawoodard** [comment]
If you're here, you might want to check out this thread for more info:
https://github.com/janjongboom/Moth/pull/17
