### ISSUE TITLE
Saving changes to css file doesn't result in cache refresh

### ISSUE THREAD

**Issue by kijanawoodard** [janjongboom/Moth#16]
As I was figuring out what was going on with my other issue ("Media Queries removed"), I realized that as I was making changes, I could simply refresh the browser. I had to rebuild all to see the changes.

I'm in VS2010 working on a fresh MVC4 project.

**Comment by janjongboom** [comment]
You'll have to wait before the cache invalidates itself before the change is pushed through (10 minutes), this is to prevent having to hash the CSS files on every request. Easiest is to disable the cache when in development.  See the [DebugProvider](https://github.com/janjongboom/Moth/wiki/Debug-flags) in the wiki.
