### ISSUE TITLE
RenderJavascript() On debug and release version.

### ISSUE THREAD

**Issue by johnlian** [janjongboom/Moth#5]
Hi, @janjongboom

For Moth, Is there an easy way to tell moth don't compress the javascript file in the development envirnment, and compress the javascript file in the production envirnment? for example we can add an configuration item in my web config file, and moth konw what i want to do.

thanks.

**Comment by janjongboom** [comment]
Yes there is. Please see the [Options](https://github.com/janjongboom/Moth/wiki/Options) page, you can make `EnableScriptMinification` be dependent on a setting in your config.

**Comment by johnlian** [comment]
Thanks.
