### ISSUE TITLE
Mvc2: Writer on ViewContext is not always HtmltextWriter

### ISSUE THREAD

**Issue by Teun** [janjongboom/Moth#7]
In my website, for some reason (not sure why), the Writer on the ViewContext has different types. Sometimes it's an HttpWriter, sometimes a StreamWriter and sometimes the HtmlTextWriter that Moth expects. This happens in perfectly normal pages with a Master page and.ascx  partial views. All of the 3 types have been observed in the same partial view (but on different pages).

The whole implementation of the InlineScriptHelper seems a bit hackish. I'm not sure what would make a better way, but this does not seem to work for every Mvc2 page.

**Comment by janjongboom** [comment]
Hi @Teun, is this always on the same pages, or is this at random? And if this is at the same pages, is there a pattern in there? Does this apply to pages that maybe use Webforms controls on them?

It's correct that there is quite some hackiness in the library, but that's because page substitution has been removed from MVC 2; and it had to be hacked in.

**Comment by Teun** [comment]
It's always on the same pages, so I'm sure it's related to something on the page, probably indeed related to using WebForms controls somewhere. Anyhow, it prevents me from using Moth right now, as part of my pages hit the line
```    // fak joe
    return;

```
```

**Comment by Teun** [comment]
Option for neater solution:
In Application_Start (or whatever turns out to be the right moment), we replace the available view engines by custom ones wrapping the originals. These return ViewEngineResults containing a custom IView wrapping the original views. Then these wrappers wrap the TextWriter that is passed to the view inside a custom TextWriter that always allows us to swap out the internal writer to redirects part of the written output.
A lot of wrapping, but I'm quite sure that it will work and will give a consistent solution for both Mvc2 and 3 without relying on type checking or even reflection.
If you think it's a good idea, I a available for implementation. But maybe there are better ways to do this than through a custom ViewEngine..

**Comment by janjongboom** [comment]
I think I have looked into that before, but I can't recall why this didn't work. I got time this weekend to dive into this.

**Comment by Teun** [comment]
Posted pull request with fix. Didn't test on Mvc3 though.
